name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build_latex:
    name: Build LaTex
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed tex files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: "./*.tex"
          use_rest_api: "true"

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
